import asyncio
import logging
import time
from pathlib import Path

from fastapi import APIRouter, HTTPException, Request, status

from app.config import settings
from app.models import CodeRequest, CodeResponse, FixRequest
from app.llm.factory import LLMFactory
from app.services.ollama_service import select_best_model
from app.utils.vector_engine import CodeVectorEngine
from database.db import is_activated

logger = logging.getLogger("codemaster-ai")
router = APIRouter(tags=["Generation"])

_vector_engine = None


def get_vector_engine() -> CodeVectorEngine:
    global _vector_engine
    if _vector_engine is None:
        repo_root = Path(__file__).resolve().parents[3]
        _vector_engine = CodeVectorEngine(repo_root)
    return _vector_engine


def build_context_prompt(query: str) -> str:
    try:
        engine = get_vector_engine()
        context_chunks = engine.search_context(query, top_k=3)
    except Exception as exc:
        logger.warning("Vector context lookup failed: %s", exc)
        return ""

    if not context_chunks:
        return ""

    formatted = "\n\n".join(f"[{index}] {chunk}" for index, chunk in enumerate(context_chunks, start=1))
    return (
        "Use the following repository context when relevant:\n"
        f"{formatted}\n"
    )


@router.post("/generate-code", response_model=CodeResponse)
async def generate_code(request: Request, payload: CodeRequest):
    """Generate clean, optimized code based on a prompt using AI models."""
    if not is_activated() and not getattr(request.app.state, "activated", False):
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="AI Agent inactive. Use /activate."
        )

    selection = select_best_model(payload.prompt, payload.language)
    chosen_model = payload.model or selection["model"]

    provider = LLMFactory.create_provider(settings.LLM_PROVIDER)
    if not provider.is_ready() and settings.LLM_PROVIDER != "ollama":
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"LLM provider '{settings.LLM_PROVIDER}' is not configured"
        )

    context_prompt = build_context_prompt(payload.prompt)
    task_prompt = (
        "You are a brutal, expert-level AI programmer.\n"
        f"Generate clean, optimized {payload.language or '[AUTO DETECTED]'} code for:\n{payload.prompt}\n"
        f"{context_prompt}"
        "Return only code. Do not include explanations or markdown fences."
    )

    start = time.time()
    try:
        if settings.LLM_PROVIDER == "ollama":
            response_text = await asyncio.wait_for(
                provider.generate(task_prompt, model=chosen_model),
                timeout=settings.GENERATION_TIMEOUT,
            )
            code = response_text or "// No code generated."
        else:
            response_text = await asyncio.wait_for(
                provider.generate(task_prompt, model=chosen_model),
                timeout=settings.GENERATION_TIMEOUT,
            )
            code = response_text or "// No code generated."
    except asyncio.TimeoutError:
        logger.exception("💥 Code generation timeout")
        raise HTTPException(
            status_code=status.HTTP_504_GATEWAY_TIMEOUT,
            detail="Code generation timed out",
        ) from None
    except Exception as ex:
        logger.exception("💥 Code generation failed")
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Code generation failed: {ex}",
        ) from ex

    elapsed = int((time.time() - start) * 1000)

    logger.info(f"✅ Generated {len(code)} chars in {elapsed}ms with {chosen_model}")
    return CodeResponse(
        code=code,
        explanation=f"Generated by {chosen_model} ({selection['reason']}).",
        confidence=0.95,
        model_used=chosen_model,
        elapsed_ms=elapsed,
    )


@router.post("/fix-code", response_model=CodeResponse)
async def fix_code(request: Request, payload: FixRequest):
    """Fix bugs and optimize code based on instructions using AI models."""
    if not is_activated() and not getattr(request.app.state, "activated", False):
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="AI Agent inactive. Use /activate."
        )

    provider = LLMFactory.create_provider(settings.LLM_PROVIDER)
    if not provider.is_ready() and settings.LLM_PROVIDER != "ollama":
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"LLM provider '{settings.LLM_PROVIDER}' is not configured"
        )

    context_prompt = build_context_prompt(payload.file_code)
    prompt = (
        "You are an expert senior developer.\n"
        f"Given this code:\n{payload.file_code}\n\n"
        f"Instructions: {payload.instructions or 'Fix all bugs and optimize for best practices.'}\n"
        f"{context_prompt}"
        "Return only the fixed code. Do not include explanations or markdown fences."
    )

    selection = select_best_model(payload.file_code, None)
    chosen_model = selection["model"]

    start = time.time()
    try:
        if settings.LLM_PROVIDER == "ollama":
            response_text = await asyncio.wait_for(
                provider.generate(prompt, model=chosen_model),
                timeout=settings.GENERATION_TIMEOUT,
            )
            code = response_text or "// No fixes generated."
        else:
            response_text = await asyncio.wait_for(
                provider.generate(prompt, model=chosen_model),
                timeout=settings.GENERATION_TIMEOUT,
            )
            code = response_text or "// No fixes generated."
    except asyncio.TimeoutError:
        logger.exception("💥 Code fix timeout")
        raise HTTPException(
            status_code=status.HTTP_504_GATEWAY_TIMEOUT,
            detail="Code fixing timed out",
        ) from None
    except Exception as exc:
        logger.exception("💥 Code fix failed")
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Code fixing failed: {exc}",
        ) from exc

    elapsed = int((time.time() - start) * 1000)

    logger.info(f"✅ Fixed code with {chosen_model} in {elapsed}ms")
    return CodeResponse(
        code=code,
        explanation=f"Fixed by {chosen_model} ({selection['reason']}).",
        confidence=0.95,
        model_used=chosen_model,
        elapsed_ms=elapsed,
    )
