"""Pydantic models for API request/response validation."""
from typing import Optional, Any, Dict

from pydantic import BaseModel, ConfigDict, Field, field_validator

from .config import settings


class Source(BaseModel):
    file: str
    snippet: str


class Provenance(BaseModel):
    cited_indices: list[int]
    sources: Dict[str, Source]
    verification_status: Optional[str] = Field(None, description="Optional verification status (e.g., 'verified')")

    @field_validator("sources", mode="after")
    @classmethod
    def validate_sources(cls, sources: Dict[str, Source]) -> Dict[str, Source]:
        for key, source in sources.items():
            if not source.snippet or not source.snippet.strip():
                raise ValueError(f"snippet for source '{key}' must not be empty")
        return sources


class CodeRequest(BaseModel):
    """Request model for code generation."""
    prompt: str = Field(
        ...,
        min_length=1,
        max_length=settings.MAX_PROMPT_LENGTH,
        description="Code generation prompt or task description"
    )
    language: Optional[str] = Field(
        None,
        description="Programming language (optional, auto-detected if not provided)"
    )
    model: Optional[str] = Field(
        None,
        description="Override automatic model selection (optional)"
    )

    model_config = ConfigDict(
        json_json_schema_extra = {
            "example": {
                "prompt": "Write a Python function to calculate Fibonacci numbers",
                "language": "python",
                "model": None
            }
        }
    )

class CodeResponse(BaseModel):
    """Response model for code generation and fixing."""
    code: str = Field(..., description="Generated or fixed code")
    explanation: str = Field(..., description="Explanation of what was generated or fixed")
    confidence: float = Field(..., ge=0.0, le=1.0, description="Confidence score (0-1)")
    model_used: str = Field(..., description="Name of the model that generated the code")
    elapsed_ms: int = Field(..., ge=0, description="Time taken in milliseconds")
    provenance: Optional[Provenance] = Field(
        None,
        description="Optional provenance metadata: cited indices and source file mapping",
    )

    model_config = ConfigDict(
        json_json_schema_extra = {
            "example": {
                "code": "def fibonacci(n):\n    if n <= 1:\n        return n\n    return fibonacci(n-1) + fibonacci(n-2)",
                "explanation": "Generated by codellama:7b-instruct (Python detected).",
                "confidence": 0.95,
                "model_used": "codellama:7b-instruct",
                "elapsed_ms": 2345
            }
        }
    )

class FixRequest(BaseModel):
    """Request model for code fixing."""
    file_code: str = Field(
        ...,
        min_length=1,
        max_length=settings.MAX_CODE_LENGTH,
        description="Code to be fixed or optimized"
    )
    instructions: Optional[str] = Field(
        None,
        max_length=1000,
        description="Specific fix instructions (optional, defaults to general bug fixes)"
    )

    model_config = ConfigDict(
        json_json_schema_extra = {
            "example": {
                "file_code": "def add(a, b):\n    return a + b + undefined_var",
                "instructions": "Fix the undefined variable error"
            }
        }
    )