"""Pydantic models for API request/response validation."""
from typing import Optional

from pydantic import BaseModel, Field

from app.config import settings


class CodeRequest(BaseModel):
    """Request model for code generation."""
    prompt: str = Field(
        ...,
        min_length=1,
        max_length=settings.MAX_PROMPT_LENGTH,
        description="Code generation prompt or task description"
    )
    language: Optional[str] = Field(
        None,
        description="Programming language (optional, auto-detected if not provided)"
    )
    model: Optional[str] = Field(
        None,
        description="Override automatic model selection (optional)"
    )

    class Config:
        json_schema_extra = {
            "example": {
                "prompt": "Write a Python function to calculate Fibonacci numbers",
                "language": "python",
                "model": None
            }
        }


class CodeResponse(BaseModel):
    """Response model for code generation and fixing."""
    code: str = Field(..., description="Generated or fixed code")
    explanation: str = Field(..., description="Explanation of what was generated or fixed")
    confidence: float = Field(..., ge=0.0, le=1.0, description="Confidence score (0-1)")
    model_used: str = Field(..., description="Name of the model that generated the code")
    elapsed_ms: int = Field(..., ge=0, description="Time taken in milliseconds")

    class Config:
        json_schema_extra = {
            "example": {
                "code": "def fibonacci(n):\n    if n <= 1:\n        return n\n    return fibonacci(n-1) + fibonacci(n-2)",
                "explanation": "Generated by codellama:7b-instruct (Python detected).",
                "confidence": 0.95,
                "model_used": "codellama:7b-instruct",
                "elapsed_ms": 2345
            }
        }


class FixRequest(BaseModel):
    """Request model for code fixing."""
    file_code: str = Field(
        ...,
        min_length=1,
        max_length=settings.MAX_CODE_LENGTH,
        description="Code to be fixed or optimized"
    )
    instructions: Optional[str] = Field(
        None,
        max_length=1000,
        description="Specific fix instructions (optional, defaults to general bug fixes)"
    )

    class Config:
        json_schema_extra = {
            "example": {
                "file_code": "def add(a, b):\n    return a + b + undefined_var",
                "instructions": "Fix the undefined variable error"
            }
        }
